### ISSUE TITLE
Lobby and Home: User types differences 

### ISSUE THREAD

**Issue by gaelledel** [vector-im/matrix-video-chat#144]
Based on the latest pushes, it seems there's some confusion for what should be displayed in the top nav bar for Home and Lobby screens so I have further clarified it here:

For **Guests (named)** on Home and Lobby:
OnClick the **user icon**:
Display ability to change guest name
Display the ability to log in

<img width="695" alt="Screenshot 2021-12-14 at 10 42 06" src="https://user-images.githubusercontent.com/76945183/145983164-d8757625-8d1e-4844-aeb8-eb92f11caf8b.png">
<img width="750" alt="Screenshot 2021-12-14 at 10 42 28" src="https://user-images.githubusercontent.com/76945183/145983224-a5f01b6a-7a4a-4372-8a48-1956c994609f.png">

For **Logged in users** on Home and Lobby:
OnClick the **user avatar**:
Display ability to change profile for name and picture
Display the ability to log out

<img width="649" alt="Screenshot 2021-12-14 at 10 45 56" src="https://user-images.githubusercontent.com/76945183/145983771-1d150e1d-5604-4a20-977a-3470ef4481c2.png">
<img width="847" alt="Screenshot 2021-12-14 at 10 46 20" src="https://user-images.githubusercontent.com/76945183/145983825-3c70269b-3aa6-491d-a70a-533514b2b827.png">

For **Anonymous guests**

We are not displaying any avatar or user icon but instead on Home and Lobby, we're displaying a log in button at the top right. 

<img width="756" alt="Screenshot 2021-12-14 at 10 50 45" src="https://user-images.githubusercontent.com/76945183/145984439-58ea53c3-491e-406c-b4d0-85d3a1269c58.png">
<img width="939" alt="Screenshot 2021-12-14 at 10 59 22" src="https://user-images.githubusercontent.com/76945183/145986001-abc3defe-4e1a-4b48-91b9-72a27aa331cb.png">

**Comment by robertlong** [comment]
> For Guests (named) on Home and Lobby:
OnClick the user icon:
Display ability to change guest name
Display the ability to log in

I really think it needs the log out item in that list as well for completeness. There's currently no flow from passwordless user to guest user and I think there probably should be.

**Comment by gaelledel** [comment]
_#Also can we remove the "New call" header state? It seems like an unnecessary header and overkill to try to track this state for new calls. For example refreshing the page, navigating to login/register and back, and joining existing calls all need to be tracked in order for this header to be accurate. We also want the extra vertical space #138_
**Yes, let's leave this**


_#@gaelledel I really think it needs the log out item in that list as well for completeness. There's currently no flow from passwordless user to guest user and I think there probably should be._
**For PW less users, the idea is that they should not have to log out because they simply don't have an account in the front end. Would they not lose their PW less user status and become anonymous/guests users if they were to clear their cookies?
The Anonymous guests should only be used when the user never used element call and happen to just join a call link. They can become PW less users if they were to create a call from their anon guest Home page though.

**Comment by jakewb-b** [comment]
I agree in principle with the need to have a flow from passwordless user -> anonymous user. However, my concern is that if we refer to that as 'log out' this is confusing because:

- A passwordless user will then see both a 'log in' button (passwordless user -> registered user) and a 'log out' button (passwordless user -> anonymous user). I don't think they'll understand this.
- I'm not sure that a passwordless user really feels that they are 'logged in' in the first place, so saying 'log out' may be unclear. 

I'd be happier if the same behaviour was referred to as something else. I wonder if it's more like 'clear account' or 'reset name' or something that more accurately gives the sense to the user of 'stop being a guest with a name, and become an anonymous guest'.

I think this flow is a low priority though so if we can't solve it right now, I'm comfortable with pushing it to post-beta and talk more about it.

**Comment by robertlong** [comment]
I've removed the logout item from the user menu in the call. Closing this issue now and we can open a new one if necessary.
