### ISSUE TITLE
Screensharing

### ISSUE THREAD

**Issue by robertlong** [vector-im/matrix-video-chat#16]
You should be able to share your screen in a conference room.

**Comment by SimonBrandner** [comment]
To be completely honest I am not really happy with how some things are laid out at the moment. I don't really see why the `VideoGrid` uses participants rather than `CallFeed`s and I find it quite screen-sharing unfriendly. Also, `CallFeed`s are slowly gaining new capabilities like voice activity detection which would somehow need to be relayed through participants which I find unnecessarily complicated.

In general, I think it would make sense to use `CallFeed`s rather than participants but perhaps I am missing something :sweat_smile:

**Comment by robertlong** [comment]
Agreed, right now the design is tackling everything from application-land, but it needs to be brought back into the SDK. In which case they should use the best concepts for the SDK (Calls/CallFeeds instead of ConferenceCalls/Participants)

**Comment by robertlong** [comment]
Implemented in https://github.com/vector-im/matrix-video-chat/commit/0c475d7bac0365b53c25faf94569eb3399483830
